apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          env:
            - name: NODE_ENV
              value: {{ .Values.backend.env.NODE_ENV | quote }}
            - name: DB_NAME
              value: {{ .Values.backend.env.DB_NAME | quote }}
            - name: DB_USER
              value: {{ .Values.backend.env.DB_USER | quote }}
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db-host
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db-password
            - name: RABBIT_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: rabbit-url
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi