apiVersion: v2
name: ecommerce
description: E-commerce application (Frontend + Backend) for Fargate EKS
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - ecommerce
  - frontend
  - backend
  - fargate
  - eks

maintainers:
  - name: Partho
    email: your-email@example.com

sources:
  - https://github.com/parthorookie/finalcorrectedthreetier
