frontend:
  replicaCount: 2
  image:
    repository: 253490759114.dkr.ecr.ap-south-1.amazonaws.com/ecommerce-frontend
    tag: "408d23d"
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

backend:
  replicaCount: 2
  image:
    repository: 253490759114.dkr.ecr.ap-south-1.amazonaws.com/ecommerce-backend
    tag: "408d23d"
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

  env:
    - name: NODE_ENV
      value: "production"

worker:
  replicaCount: 1
  image:
    repository: 253490759114.dkr.ecr.ap-south-1.amazonaws.com/ecommerce-worker
    tag: "408d23d"
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

# Fargate Optimized - No node-specific scheduling
service:
  type: ClusterIP

# Ingress is handled by ALB in Terraform/CD pipeline
ingress:
  enabled: false