networks:
  ecommerce:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:
  prometheus_data:
  grafana_data:

services:

  postgres:
    image: postgres:15-alpine
    networks: [ecommerce]
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    networks: [ecommerce]
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 15s
      timeout: 10s
      retries: 5

  backend:
    build: ./app/backend
    networks: [ecommerce]
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ecommerce
      DB_USER: postgres
      DB_PASS: postgres
      RABBIT_URL: amqp://admin:admin123@rabbitmq:5672
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  worker:
    build: ./app/worker
    networks: [ecommerce]
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ecommerce
      DB_USER: postgres
      DB_PASS: postgres
      RABBIT_URL: amqp://admin:admin123@rabbitmq:5672
      MAX_RETRIES: 5
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      backend:
        condition: service_started
    restart: unless-stopped

  frontend:
    build: ./app/frontend
    networks: [ecommerce]
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_started   # ✅ IMPORTANT FIX
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.48.1
    networks: [ecommerce]
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.2.2
    networks: [ecommerce]
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped