## rabbitmq.conf — loaded at container start
loopback_users.guest = false
management.load_definitions = /etc/rabbitmq/definitions.json

## Enable Prometheus plugin
prometheus.return_per_object_metrics = true
